<a href="https://colab.research.google.com/github/DannyJS-933/Python_First_code/blob/main/FirstGoogleColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Desde 0 hasta antes del 20 pero de 5 en 5 0=> inicio, 20=> final y 5=> el conteo

In [9]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

In [10]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
a = np.arange(10)

In [12]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Organizar los datos con .reshape, en el ejemplo es 5 filas y dos columnas. No pueden sobrar los datos


In [13]:
a.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
b = np.arange(16)


In [15]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

En este ejemplo creamos una matriz cuadrada 

In [26]:
b = b.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
b[0]

array([0, 1, 2, 3])

linspace nos permite obtener valores dentro de un rango, por ejemplo de entre el 0 y hasta el uno deme 4 valores

In [31]:
np.linspace(0,1,4)

c = np.linspace(4,10, 5)
c

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

tomar el tiempo el tiempo de mi linea de codigo de mi arreglo con %time

In [32]:
mi_arreglo = np.arange(1_000_000)
mi_lista = list(range(1_000_000))

%time for i in range(10): resultado_arreglo = mi_arreglo * 2 

CPU times: user 14.5 ms, sys: 6.07 ms, total: 20.5 ms
Wall time: 20.4 ms


tomar el tiempo de mi linea de codigo de la lista 

In [33]:
%time for i in range(10): resultado_lista = [x * 2 for x in mi_lista]

CPU times: user 806 ms, sys: 198 ms, total: 1 s
Wall time: 1.01 s


Numeros random con Nunpy
y tener un promedio de 10, 3 y 20

In [35]:
mean = 10
stdev = 3
number_value = 20
mi_arreglo = np.random.normal(mean, stdev, number_value)

In [39]:
mi_arreglo.mean()
mi_arreglo.std()


2.0768148551663668

numeros aleatorios y enteros

In [42]:
np.random.randint(1,10,5)

array([2, 7, 5, 5, 1])

Creo el array y escojo de forma aleatoria a una fruta

In [43]:
frutas = np.array(['pera', 'manzana', 'yuca', 'tiquisque', 'pina'])

In [50]:
np.random.choice(frutas, 1)


array(['pina'], dtype='<U9')