<a href="https://colab.research.google.com/github/DannyJS-933/Python_First_code/blob/main/GoogleColabProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercises

#### Create an array from 0 to 26 assign it to a variable x

In [4]:
import numpy as np


In [25]:
x = np.arange(27)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#### Reverse the order of the array and print it out

In [27]:
x_reverse = x[::-1]
print(x_reverse)

[26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


#### Convert the 1-dimensional array you created into a 3 dimensional array

In [29]:
x_dimensional= x.reshape(3,9)
print(x_dimensional)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


#### Find the index (location) for value 12

In [32]:
x_position = x_dimensional[1,3]
x_position

12

#### Create a random shuffled list of values from 0-19 and assign it to variable y

In [40]:
y = np.random.permutation(19)
y

array([13,  4, 14,  9, 15,  6,  3,  8, 10, 16, 12,  2, 17,  0,  7,  5, 18,
       11,  1])

#### Create an array of boolean values for values in y that are greater than 10

In [43]:
condition = y > 10
print(condition)
y[condition]

[ True False  True False  True False False False False  True  True False
  True False False False  True  True False]


array([13, 14, 15, 16, 12, 17, 18, 11])

#### Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5

In [6]:
mean = 10
stadev = 3
randomSample = 10
np.random.normal(mean, stadev, randomSample)

array([ 6.12922646,  9.62031582, 11.58613184,  5.68168599, 12.25305087,
        8.6095721 , 10.44953284,  9.87908341, 15.43436405,  5.70197621])

Calcular el precio final de un arreglo de precio si el descuento es el 15%

In [5]:
precio = np.array([2100,150,400,300,150])

In [8]:
total = precio * .85
total

array([1785. ,  127.5,  340. ,  255. ,  127.5])